### ISSUE TITLE
What KAN I say, Mamba NEVER Out!

### ISSUE THREAD

**Issue by lif314** [yuweihao/MambaOut#10]

**Comment by cxchhh** [comment]
<img width="552" alt="image" src="https://github.com/yuweihao/MambaOut/assets/35392417/5007f8e4-b729-4212-a1e2-c6ba3a577464">

**Comment by wqtwjt1996** [comment]
> <img alt="image" width="552" src="https://private-user-images.githubusercontent.com/35392417/330307153-5007f8e4-b729-4212-a1e2-c6ba3a577464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDkyMDYsIm5iZiI6MTcxNTcwODkwNiwicGF0aCI6Ii8zNTM5MjQxNy8zMzAzMDcxNTMtNTAwN2Y4ZTQtYjcyOS00MjEyLWExZTItYzZiYTNhNTc3NDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE3NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNWM3NzQ0Mjc1MjVhNjFmNTk1YmE4OWViNjNjZGUyYjg4YTQ1OTk0ZTJmMjYxY2YzMWMxM2ZkZTZkM2JlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNJfXhII_6ZtP6IKGzyldqUCUstHe2UF4dKNz_7Zs30">

夺笋呐
